# Generated by Django 4.0.6 on 2022-07-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_resourcetype_alter_library_options_course_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='level',
        ),
        migrations.AddField(
            model_name='material',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
