# Generated by Django 4.0.6 on 2022-07-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_material_lecturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
    ]
