# Generated by Django 4.0.6 on 2022-08-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_material_description_material_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='impressions',
        ),
    ]
