# Generated by Django 4.0.6 on 2022-08-18 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0008_remove_material_impressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='user_library',
            field=models.ManyToManyField(blank=True, related_name='user_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
